package com.github.javahello.erm.example.mapper;

import com.github.javahello.erm.example.model.SysConfig;
import com.github.javahello.erm.example.model.SysConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    long countByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int deleteByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int deleteByPrimaryKey(String confId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int insertSelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    List<SysConfig> selectByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    SysConfig selectByPrimaryKey(String confId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int updateByExample(@Param("record") SysConfig record, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    int updateByPrimaryKey(SysConfig record);
}