package com.github.javahello.erm.example.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CONFIG.CONF_ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private String confId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CONFIG.CONF_VALUE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private String confValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CONFIG.USE_RATE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private BigDecimal useRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CONFIG.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_CONFIG.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private Date lastModifiedDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CONFIG.CONF_ID
     *
     * @return the value of USER_CONFIG.CONF_ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public String getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CONFIG.CONF_ID
     *
     * @param confId the value for USER_CONFIG.CONF_ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setConfId(String confId) {
        this.confId = confId == null ? null : confId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CONFIG.CONF_VALUE
     *
     * @return the value of USER_CONFIG.CONF_VALUE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public String getConfValue() {
        return confValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CONFIG.CONF_VALUE
     *
     * @param confValue the value for USER_CONFIG.CONF_VALUE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setConfValue(String confValue) {
        this.confValue = confValue == null ? null : confValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CONFIG.USE_RATE
     *
     * @return the value of USER_CONFIG.USE_RATE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public BigDecimal getUseRate() {
        return useRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CONFIG.USE_RATE
     *
     * @param useRate the value for USER_CONFIG.USE_RATE
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setUseRate(BigDecimal useRate) {
        this.useRate = useRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CONFIG.CREATED_DATETIME
     *
     * @return the value of USER_CONFIG.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CONFIG.CREATED_DATETIME
     *
     * @param createdDatetime the value for USER_CONFIG.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_CONFIG.LAST_MODIFIED_DATETIME
     *
     * @return the value of USER_CONFIG.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public Date getLastModifiedDatetime() {
        return lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_CONFIG.LAST_MODIFIED_DATETIME
     *
     * @param lastModifiedDatetime the value for USER_CONFIG.LAST_MODIFIED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setLastModifiedDatetime(Date lastModifiedDatetime) {
        this.lastModifiedDatetime = lastModifiedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_CONFIG
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", confId=").append(confId);
        sb.append(", confValue=").append(confValue);
        sb.append(", useRate=").append(useRate);
        sb.append(", createdDatetime=").append(createdDatetime);
        sb.append(", lastModifiedDatetime=").append(lastModifiedDatetime);
        sb.append("]");
        return sb.toString();
    }
}