package com.github.javahello.erm.example.model;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.UNAME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.ID_NO
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    private String idNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.ID
     *
     * @return the value of USER_INFO.ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.ID
     *
     * @param id the value for USER_INFO.ID
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.UNAME
     *
     * @return the value of USER_INFO.UNAME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.UNAME
     *
     * @param uname the value for USER_INFO.UNAME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.CREATED_DATETIME
     *
     * @return the value of USER_INFO.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.CREATED_DATETIME
     *
     * @param createdDatetime the value for USER_INFO.CREATED_DATETIME
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.ID_NO
     *
     * @return the value of USER_INFO.ID_NO
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.ID_NO
     *
     * @param idNo the value for USER_INFO.ID_NO
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Sun Dec 27 18:16:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uname=").append(uname);
        sb.append(", createdDatetime=").append(createdDatetime);
        sb.append(", idNo=").append(idNo);
        sb.append("]");
        return sb.toString();
    }
}